### ISSUE TITLE
No such file or directory: 'data/natasha/text_handler_natasha.yaml'

### ISSUE THREAD

**Issue by luckydevil13** [sovaai/sova-tts#1]
```2020-11-19T17:02:21.109307200Z FileNotFoundError: [Errno 2] No such file or directory: 'data/natasha/text_handler_natasha.yaml'
2020-11-19T17:02:21.109625000Z [2020-11-19 17:02:21 +0000] [9] [INFO] Worker exiting (pid: 9)
2020-11-19T17:02:21.300224100Z [2020-11-19 17:02:21 +0000] [6] [INFO] Shutting down: Master
2020-11-19T17:02:21.300242800Z [2020-11-19 17:02:21 +0000] [6] [INFO] Reason: Worker failed to boot.
2020-11-19T17:03:21.697435800Z [2020-11-19 17:03:21 +0000] [6] [INFO] Starting gunicorn 19.9.0
2020-11-19T17:03:21.697717300Z [2020-11-19 17:03:21 +0000] [6] [INFO] Listening at: http://0.0.0.0:8899 (6)
2020-11-19T17:03:21.697733800Z [2020-11-19 17:03:21 +0000] [6] [INFO] Using worker: sync
2020-11-19T17:03:21.699592900Z [2020-11-19 17:03:21 +0000] [9] [INFO] Booting worker with pid: 9
2020-11-19T17:03:22.809374300Z 2020-11-19 17:03:22.808 | INFO     | modules.tts.synthesizer:_load_text_handler:278 - Loading text handler
2020-11-19T17:03:22.809740200Z [2020-11-19 17:03:22 +0000] [9] [ERROR] Exception in worker process
2020-11-19T17:03:22.809753800Z Traceback (most recent call last):
2020-11-19T17:03:22.809759000Z   File "/usr/local/lib/python3.6/dist-packages/gunicorn/arbiter.py", line 583, in spawn_worker
2020-11-19T17:03:22.809763300Z     worker.init_process()
2020-11-19T17:03:22.809767000Z   File "/usr/local/lib/python3.6/dist-packages/gunicorn/workers/base.py", line 129, in init_process
2020-11-19T17:03:22.809771100Z     self.load_wsgi()
2020-11-19T17:03:22.809775000Z   File "/usr/local/lib/python3.6/dist-packages/gunicorn/workers/base.py", line 138, in load_wsgi
2020-11-19T17:03:22.809779600Z     self.wsgi = self.app.wsgi()
2020-11-19T17:03:22.809781900Z   File "/usr/local/lib/python3.6/dist-packages/gunicorn/app/base.py", line 67, in wsgi
2020-11-19T17:03:22.809784200Z     self.callable = self.load()
2020-11-19T17:03:22.809786400Z   File "/usr/local/lib/python3.6/dist-packages/gunicorn/app/wsgiapp.py", line 52, in load
2020-11-19T17:03:22.809788600Z     return self.load_wsgiapp()
2020-11-19T17:03:22.809790800Z   File "/usr/local/lib/python3.6/dist-packages/gunicorn/app/wsgiapp.py", line 41, in load_wsgiapp
2020-11-19T17:03:22.809793100Z     return util.import_app(self.app_uri)
2020-11-19T17:03:22.809805300Z   File "/usr/local/lib/python3.6/dist-packages/gunicorn/util.py", line 350, in import_app
2020-11-19T17:03:22.809807700Z     __import__(module)
2020-11-19T17:03:22.809809500Z   File "/sova-tts/app.py", line 6, in <module>
2020-11-19T17:03:22.809811700Z     from models import models
2020-11-19T17:03:22.809814100Z   File "/sova-tts/models.py", line 7, in <module>
2020-11-19T17:03:22.809816100Z     natasha = Synthesizer.from_config(config, name="natasha")
2020-11-19T17:03:22.809818100Z   File "/sova-tts/modules/tts/synthesizer.py", line 225, in from_config
2020-11-19T17:03:22.809820000Z     params["text_handler"] = _load_text_handler(modules_config["text_handler"])
2020-11-19T17:03:22.809822300Z   File "/sova-tts/modules/tts/synthesizer.py", line 285, in _load_text_handler
2020-11-19T17:03:22.809824400Z     handler_config = Synthesizer.load_config(config_dict["config_path"])
2020-11-19T17:03:22.809826500Z   File "/sova-tts/modules/tts/synthesizer.py", line 258, in load_config
2020-11-19T17:03:22.809828500Z     with open(config_source, "r", encoding="utf-8") as stream:
2020-11-19T17:03:22.809830500Z FileNotFoundError: [Errno 2] No such file or directory: 'data/natasha/text_handler_natasha.yaml'
2020-11-19T17:03:22.810173400Z [2020-11-19 17:03:22 +0000] [9] [INFO] Worker exiting (pid: 9)
2020-11-19T17:03:22.986903800Z [2020-11-19 17:03:22 +0000] [6] [INFO] Shutting down: Master
2020-11-19T17:03:22.986929200Z [2020-11-19 17:03:22 +0000] [6] [INFO] Reason: Worker failed to boot.```

**Comment by Dekakhrone** [comment]
Hello, @luckydevil13! You need to clone the last version of the [repository](https://github.com/sovaai/sova-tts/commit/a8da6887719f2b940cea84663deb00259bc4d27a), then redownload and unpack data archive. Both have been updated.
```
$ git clone --recursive https://github.com/sovaai/sova-tts.git
$ cd sova-tts/
$ wget http://dataset.sova.ai/SOVA-TTS/Data.tar
$ tar -xvf Data.tar && rm Data.tar
```
