### ISSUE TITLE
How to properly run your code using python 'executable_filename.py' ?

### ISSUE THREAD

**Issue by yerzhan7orazayev** [sovaai/sova-tts#3]

**Comment by yerzhan7orazayev** [comment]
I am trying to run `example.py` by properly providing parameters to `modules/data/config.yaml`.
However, I am getting the following error message:

```
C:\Users\DELL\anaconda3\envs\sova-tts\python.exe C:/Users/DELL/sova-tts/modules/tts/example.py
2021-03-14 01:58:05.214 | INFO     | synthesizer:_load_text_handler:282 - Loading text handler
{'voice_control_cfg': 'data/voice.yaml', 'user_dict': 'C:/Users/DELL/sova-tts/data/natasha/natasha_user_dict.json', 'text_handler': {'config_path': 'C:/Users/DELL/sova-tts/data/natasha/text_handler_natasha.yaml', 'out_max_length': 200}, 'modules': {'engine': 'tacotron2', 'vocoder': 'waveglow'}, 'engine': {'tacotron2': {'model_path': 'C:/Users/DELL/sova-tts/data/natasha/checkpoint_natasha', 'hparams_path': 'C:/Users/DELL/sova-tts/data/natasha/hparams.yaml', 'options': {'steps_per_symbol': 10, 'gate_threshold': 0.5}}}, 'vocoder': {'waveglow': {'model_path': 'C:/Users/DELL/sova-tts/data/natasha/waveglow_ljs_nvidia.pt', 'options': {'sigma': 0.666, 'strength': 0.1}}}}
2021-03-14 01:58:18.435 | INFO     | synthesizer:module_from_config:241 - Loading tacotron2 module
model_path is C:/Users/DELL/sova-tts/data/natasha/checkpoint_natasha
dict_keys(['iteration', 'state_dict', 'optimizer', 'lr_scheduler', 'hparams'])
2021-03-14 01:58:26.456 | INFO     | synthesizer:module_from_config:241 - Loading waveglow module
C:\Users\DELL\anaconda3\envs\sova-tts\lib\site-packages\torch\serialization.py:656: SourceChangeWarning: source code of class 'glow.WaveGlow' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
C:\Users\DELL\anaconda3\envs\sova-tts\lib\site-packages\torch\serialization.py:656: SourceChangeWarning: source code of class 'torch.nn.modules.conv.ConvTranspose1d' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
C:\Users\DELL\anaconda3\envs\sova-tts\lib\site-packages\torch\serialization.py:656: SourceChangeWarning: source code of class 'torch.nn.modules.container.ModuleList' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
C:\Users\DELL\anaconda3\envs\sova-tts\lib\site-packages\torch\serialization.py:656: SourceChangeWarning: source code of class 'torch.nn.modules.conv.Conv1d' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
dict_keys(['model'])
C:/Users/DELL/sova-tts/data/natasha/natasha_user_dict.json
2021-03-14 01:58:48.691 | INFO     | synthesizer:load_user_dict:189 - User dictionary has been loaded
2021-03-14 01:58:48.692 | INFO     | synthesizer:__init__:64 - Synthesizer tacotron2 is ready
2021-03-14 01:58:48.692 | INFO     | synthesizer:synthesize:68 - Съешь же ещё этих мягких французских булок да выпей чаю.
mask_stress: False
mask_phonemes: False
kwargs: {}
['съ+ешь же ещё +этих м+ягких франц+узских б+улок да в+ыпей чаю.']
unit: съ+ешь же ещё +этих м+ягких франц+узских б+улок да в+ыпей чаю.
Traceback (most recent call last):
  File "C:/Users/DELL/sova-tts/modules/tts/example.py", line 25, in <module>
    test()
  File "C:/Users/DELL/sova-tts/modules/tts/example.py", line 17, in test
    audio = tacotron.synthesize(
  File "C:\Users\DELL\sova-tts\modules\tts\synthesizer.py", line 82, in synthesize
    audio_list = list(self._generate_audio(sequence, **kwargs))
  File "C:\Users\DELL\sova-tts\modules\tts\synthesizer.py", line 109, in _generate_audio
    if unit in Delimiter:
  File "C:\Users\DELL\anaconda3\envs\sova-tts\lib\enum.py", line 352, in __contains__
    raise TypeError(
TypeError: unsupported operand type(s) for 'in': 'str' and 'EnumMeta'

Process finished with exit code 1
```
Could you please kindly help me to resolve this issue?

**Comment by Dekakhrone** [comment]
Hello @yerzhan7orazayev! It seems that you have python>3.7 installed, which is incompatible with some code in earlier versions. I suggest you check out the new version 1.1: you may either launch the application without docker `python3 app.py` or launch just a script `python3 test.py` (both methods requires all necessary dependencies installed)
